name: CI - Build & Push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: compose-basics-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute image name and tags (lowercase owner)
        id: vars
        run: |
          OWNER_RAW='${{ github.vvvsanych }}'
          OWNER_LC=$(echo "$OWNER_RAW" | tr '[:upper:]' '[:lower:]')
          echo "OWNER_LC=$OWNER_LC" >> $GITHUB_ENV

          IMAGE="${{ env.REGISTRY }}/${OWNER_LC}/${{ env.IMAGE_NAME }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

          TAGS="$IMAGE:sha-${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS="$TAGS,$IMAGE:latest"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and push (with SBOM & provenance)
        uses: docker/build-push-action@v6
        with:
          context: ./phase1/compose-basics/app
          push: true
          tags: ${{ env.TAGS }}
          sbom: true
          provenance: true

      - name: Trivy scan (CRITICAL/HIGH, не валимо збірку)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE }}:sha-${{ github.sha }}
          format: table
          vuln-type: os,library
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Show image and tags
        run: |
          echo "IMAGE: ${{ env.IMAGE }}"
          echo "TAGS:  ${{ env.TAGS }}"
