name: CI - Build & Push to GHCR

on:
  push:
    branches: [ "main" ]
  pull_request: {}

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  OWNER: vvvsanych         # <<< заміни на свій нік, тільки lower-case!
  IMAGE_NAME: compose-basics-app
  CONTEXT_DIR: ./phase1/compose-basics/app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Формуємо повне ім'я образу та теги БЕЗ «магії»
      - name: Compute image and tags (simple)
        run: |
          IMAGE="${{ env.REGISTRY }}/${{ env.OWNER }}/${{ env.IMAGE_NAME }}"
          # завжди тег з sha; latest — тільки для main
          TAGS="$IMAGE:sha-${{ github.sha }}"
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            TAGS="$TAGS,$IMAGE:latest"
          fi
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          echo "TAGS=$TAGS" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT_DIR }}
          push: true
          tags: ${{ env.TAGS }}

      - name: Show what we pushed
        run: |
          echo "IMAGE: ${{ env.IMAGE }}"
          echo "TAGS:  ${{ env.TAGS }}"
